// <auto-generated />
namespace GarageReturn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1212));
        
        string IMigrationMetadata.Id
        {
            get { return "201805251012397_1212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
